# Generated by Django 3.2.15 on 2023-05-09 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Objeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Criado')),
                ('alterado', models.DateField(auto_now=True, verbose_name='Alterado')),
                ('numero_de_id', models.PositiveIntegerField(verbose_name='Numero de ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('valor_estimado', models.FloatField(verbose_name='Valor Estimado')),
                ('peso', models.FloatField(verbose_name='Peso')),
            ],
            options={
                'verbose_name': 'Objeto',
                'verbose_name_plural': 'Objetos',
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Criado')),
                ('alterado', models.DateField(auto_now=True, verbose_name='Alterado')),
                ('numero_de_id', models.PositiveIntegerField(verbose_name='Numero de ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('cpf', models.IntegerField(verbose_name='CPF')),
                ('email', models.EmailField(max_length=255, verbose_name='Email')),
                ('telefone', models.PositiveIntegerField(verbose_name='Telefone')),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
            },
        ),
        migrations.CreateModel(
            name='TipoObjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Criado')),
                ('alterado', models.DateField(auto_now=True, verbose_name='Alterado')),
                ('tipo', models.CharField(max_length=255, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'TipoObjeto',
                'verbose_name_plural': 'TipoObjetos',
            },
        ),
        migrations.CreateModel(
            name='TipoPessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Criado')),
                ('alterado', models.DateField(auto_now=True, verbose_name='Alterado')),
                ('tipo', models.CharField(max_length=255, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'TipoPessoa',
                'verbose_name_plural': 'TipoPessoas',
            },
        ),
        migrations.CreateModel(
            name='PossePessoaObjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Criado')),
                ('alterado', models.DateField(auto_now=True, verbose_name='Alterado')),
                ('numero_de_id', models.PositiveIntegerField(verbose_name='Numero de ID')),
                ('id_objeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_objeto', to='objetos_pessoas.objeto')),
                ('id_pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_pessoa', to='objetos_pessoas.pessoa')),
            ],
            options={
                'verbose_name': 'PossePessoaObjeto',
                'verbose_name_plural': 'PossePessoaObjetos',
            },
        ),
        migrations.AddField(
            model_name='pessoa',
            name='tipo_pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipo_pessoa', to='objetos_pessoas.tipopessoa'),
        ),
        migrations.AddField(
            model_name='objeto',
            name='tipo_objeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipo_objeto', to='objetos_pessoas.tipoobjeto'),
        ),
    ]
