# Generated by Django 3.2.15 on 2023-05-10 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objetos_pessoas', '0002_tipoobjeto_multiplas_posses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoobjeto',
            name='multiplas_posses',
            field=models.BooleanField(default=True, verbose_name='Pode ter múltiplas posses?'),
        ),
        migrations.CreateModel(
            name='PermissaoPosse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Criado')),
                ('alterado', models.DateField(auto_now=True, verbose_name='Alterado')),
                ('permissao', models.BooleanField(default=False)),
                ('tipo_objeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objetos_pessoas.tipoobjeto')),
                ('tipo_pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objetos_pessoas.tipopessoa')),
            ],
            options={
                'verbose_name': 'PermissaoPosse',
                'verbose_name_plural': 'PermissoesPosse',
            },
        ),
    ]
